## async 和 await

```js
    // async里边可以没有await，但有await,外层得有async
    // async只能await同一个async函数里的await
    // async函数是返回的promise对象
    // await后边只能跟promise对象
    // await跟的这个promise对象需要调用resolve或者reject才能进行下一步
    // 捕捉错误用try catch


```




## promise

```js

// 传入一个函数，该函数有两个参数， resolve reject，
    // 若不传函数，会报错 Promise resolver undefined is not a function
    // 三个状态 pending fulfilled rejected
    let p1 = new Promise((resolve,reject)=>{
        // resolve(1)
    })

    console.log(p1)

    // then有两个参数 都是函数，第一个是onResolved的回调函数,第二个是onRejected的回调函数
    // 有三种返回值 不过都是promise对象
    // -- 第一种不返还，promise改为resolve状态，PromiseValue 为undefined
    // -- 第二种返回普通值 ,promise改为resolve状态，PromiseValue 为该普通值
    // -- 第三种返回promise,promise的状态和值取决于返回值的promise状态和值
    let res = p1.then((res)=>{ 
        // console.log(res)
        // return 123;
        return new Promise(()=>{

        })
    },function(err){
        // console.log(err)
    })
    console.log(res)

    // 可以通过catch统一捕捉错误处理
    // p1.then(()=>{

    // }).then(()=>{

    // }).catch((err)=>{
    //     console.log(err)
    // })

    //写法错误，resolve是Promise上的静态方法
    // let p2 = new Promise(()=>{}).resolve()
    // (intermediate value).resolve is not a function
    // console.log(p2)

    // 相当于一个let p1 = new Promise((resolve,reject)=>{resolve(1)})
    // 简写了上边的方法，函数参数内部仅调用了resolve(1);Promise.reject()同理

    let p2 = Promise.resolve(1)
    console.log(p2)
    let p3 = p2.then()
    console.log(p3)

    console.log("*********************************")
    // Promise.all()
    let pp1 = new Promise((resolve,reject)=>{
        resolve(1)
        // reject(10)
    })
    let pp2 = new Promise((resolve,reject)=>{
        resolve(2)
        // reject(2)
    })
    // 返回的是一个promise对象，只有都resolve之后 state才能成为fulfilled,只要调用了一个reject则状态改为rejected,不调用返回pending
    // 返回的value值是resolve返回结果合成一个数组，pending时候是undefined ，rejected时报错
    let pp3 = Promise.all([pp1,pp2])
    console.log(pp3)
    pp3.then((res)=>{
        console.log(res)
    })

    // 先拿到执行快的结果；pp1,pp2都会执行，pp4就哪个先返回就返回哪个
    let pp4 = Promise.race([pp1,pp2])
    console.log(pp4)
    // 这里就相当于快的那个的promise调用then方法
    pp4.then((res)=>{
        console.log(res)
    })

    // finally 全部执行完成,最后调用
    pp4.then((res)=>{
        console.log(res)
    }).catch((err)=>{
        console.log(err)
    }).finally((res)=>{
        console.log(res) //undefined
        console.log("全部执行完成")
    })


```


## 迭代器

```js

 // for of循环，只能遍历迭代器
    let obj = {
        a:1,
        b:2,
        c:3
    }

    // 1.Uncaught TypeError: obj is not iterable
    // for(let i of obj){
    // }

    // // 2.那如何让obj也能使用for of迭代器呢
    // obj[Symbol.iterator] = function(){

    // }
    // // Result of the Symbol.iterator method is not an object 结果符号.迭代器方法不是对象
    // for(let i of obj){
    // }


    // // 3.返回的对象里边需要有个方法（ undefined is not a function ）
    // obj[Symbol.iterator] = function(){
    //     return {}   
    // }
    // // Uncaught TypeError: undefined is not a function 
    // for(let i of obj){
    // }

    //4.迭代器的结果不是一个对象
    // obj[Symbol.iterator] = function(){
    //     return {
    //         next(){

    //         }
    //     }   
    // }
    // // Iterator result undefined is not an object
    // for(let i of obj){
    // }

    //  //5.陷入死循环 但是没有报错
    //  obj[Symbol.iterator] = function(){
    //     return {
    //         next(){
    //             return {}
    //         }
    //     }   
    // }
    // // 
    // for(let i of obj){
    // }

     //6.没有报错说明大致是这个框架，需要在返回的内容中做处理
    /*
        done表示迭代器是否完成，value是遍历的返回值
        返回的对象结果
        {
            done:true/false,
            value:val
        }
        所以需要处理的就是value的值，和done什么时候结束
    */  
     obj[Symbol.iterator] = function(){
        let keys = Object.keys(obj)
        let index = 0
        return {
            next(){
                if(index < keys.length){
                    return {
                        done:false,
                        value:{
                            key:keys[index],
                            value:obj[keys[index++]]
                        }
                    }
                }else{
                    return {
                        done:true
                    }
                }
            }
        }
    }
    let a = obj[Symbol.iterator]()
    console.log(a) //一个包含next方法的对象
    console.log(a.next())
    console.log(a.next())
    console.log(a.next())
    console.log(a.next()) //最后一次是done:true

    // // 有返回值
    // for(let i of obj){
    //     console.log(i)
    // }


```



## generator


```js

  // 定义一个generator函数，*号相当于async，yeild相当于await（但还是有区别，后边跟的返回值返回promise才并执行了resolve或者reject也不会默认执行next方法）
    // 需要通过调用fn.next()，执行下一次
    // function *fn(){
    //     yield 1
    //     yield 2
    //     yield 3
    // }
    // let f = fn()
    // console.log(f.next())
    // console.log(f.next())
    // console.log(f.next())
    // console.log(f.next())
    // console.log(f.next())
    // 可以迭代
    // for(let i of f){
    //     console.log(i)
    // }



    function * fn(){
        yield new Promise((resolve)=>{
            setTimeout(()=>{
                resolve(1)
                // console.log(1)
            },3000)
        })
        yield new Promise((resolve)=>{
            setTimeout(()=>{
                resolve(2)
                // console.log(2)
            },2000)
        })
        yield new Promise((resolve)=>{
            setTimeout(()=>{
                resolve(3)
                // console.log(3)
            },1000)
        })
    }
    // let a  = fn()
    // console.log(a)
    // console.log(a.next())

    // 这个函数实现是传入一个 generator函数，并执行他的next方法，因为需要递归调用next,写入一个函数里，通过出口来判断停止条件，通过传入的函数的参数为promise对象，来控制异步回调
    function co(fn){
        let a  = fn()
        next()
        function next(data){
            let result = a.next()
            if(!result.done){
                result.value.then((info)=>{
                    console.log(info,data);
                    next(info)
                })
            }
        }
    }
    co(fn)

```